# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Buenavista' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  # Pods for Buenavista
  pod 'Firebase/Analytics'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/Messaging'
  # Hotfix Push Notifications
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  

  # pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  post_install do |installer|
    rnfirebase = installer.pods_project.targets.find { |target| target.name == 'RNFirebase' }
    rnfirebase.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) ${PODS_ROOT}/Headers/Public/**'
    end
  end

  target 'BuenavistaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Buenavista-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buenavista-tvOS

  target 'Buenavista-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


